import "../styles/globals.css";
import { Inter } from "@next/font/google";
import Head from "next/head";
import UserLayout from "../components/users/UserLayout";
import WebLayout from "../components/WebLayout/WebLayout";

const inter = Inter({
    weight: ['400', "500"],
    style: ['normal'],
    subsets: ["latin"],
    variable: '--font-inter'
 });

export default function App({ Component, pageProps }) {

    if (Component.getLayout) {
        return Component.getLayout(

            <WebLayout>
                <main className={inter.className}>
                    <UserLayout>
                        <Component {...pageProps} />
                    </UserLayout>
                </main>
            </WebLayout>


        );
    }

    return (
        <>
            <Head>
                <title>Shoplover</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>

            <WebLayout>
                <main className={inter.className}>
                    <Component {...pageProps} />
                </main>
            </WebLayout>
        </>
    );
}
